language: c
dist: bionic
git:
  submodules: false
addons:
  apt:
    packages:
    - bzip2
    - lzip
    - zstd
before_install:
  - sudo install -dv /home/glaucus
  - cd /home/glaucus
  - sudo git clone https://github.com/glaucuslinux/glaucus .
  - sudo dash scripts/initialize
install:
  - sudo curl -Lo toolchain-22042020.tar.zstd https://github.com/glaucuslinux/toolchain/releases/download/22042020/toolchain-22042020.tar.zstd
  - sudo printf '2aa83371a2ea23a897774a599245b408982043fa02da632849c9eb06c7d14e0b9ac540dacb9feab99be7e0e6629d70ca783f355959d6ce412974b6fe75903345  toolchain-22042020.tar.zstd' | sha512sum -c
  - sudo rm -frv toolchain
  - sudo tar -I "zstd --long=31" -xvf toolchain-22042020.tar.zstd -C .
script:
  - sudo sed 's/tar xvf/sudo tar xf/' -i scripts/fetch
  - export CERD=cerata
  - export SCRD=scripts
  - export SRCD=sources
  - export MKDIR='/usr/bin/install -dv'
  - sudo dash $SCRD/toolchain/cross/check
  - sudo dash $SCRD/toolchain/native/check
  - sudo dash $SCRD/chroot/check
  - sudo dash $SCRD/system/check
