language: c
dist: bionic
git:
  submodules: false
addons:
  apt:
    packages:
    - bzip2
    - lzip
    - zstd
before_install:
  - sudo git clone https://github.com/glaucuslinux/glaucus
  - cd glaucus
  - ls -l
  - which dash
  - ls -l scripts
  - dash scripts/initialize
install:
  - sudo make toolchain
script:
  - sudo make system
